# Generated by Django 3.2.6 on 2021-08-30 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('job_id', models.IntegerField(help_text='Unique Job Id', primary_key=True, serialize=False)),
                ('job_name', models.CharField(help_text='Batch job name', max_length=150)),
                ('job_enabled', models.BooleanField(default=True, help_text='Is the job enabled or disabled?')),
                ('job_cron', models.CharField(help_text='Cron Express for a job', max_length=250)),
                ('job_run_lag_check', models.IntegerField(help_text='Running lag check in seconds')),
                ('job_status', models.IntegerField(choices=[(0, 'COMPLETED'), (1, 'RUNNING'), (2, 'FAILED')])),
                ('job_content', models.TextField(blank=True, help_text='Job Completion content', max_length=1200, null=True)),
                ('last_updated_ts', models.DateTimeField(default=django.utils.timezone.now, help_text='Job last executed timestamp')),
            ],
            options={
                'db_table': 'batch_jobs',
            },
        ),
    ]
